profile: $TAP_PROFILE
ceip_policy_disclosed: true # Installation fails if this is set to 'false'

buildservice:
  kp_default_repository: "index.docker.io/$DOCKER_USERNAME/build-service" # Create a repo here called 'build-service'
  kp_default_repository_username: "$DOCKER_USERNAME"
  kp_default_repository_password: "$DOCKER_PASSWORD"
  tanzunet_username: "$INSTALL_REGISTRY_USERNAME"
  tanzunet_password: "$INSTALL_REGISTRY_PASSWORD"
  descriptor_name: "$BUILDSERVICE_TYPE"
  enable_automatic_dependency_updates: true

supply_chain: $SUPPLY_CHAIN_TYPE

ootb_supply_chain_basic:
  registry:
    server: "$BUILD_REGISTRY_HOSTNAME"
    repository: "$DOCKER_USERNAME"
  gitops:
    ssh_secret: ""

metadata_store:
  app_service_type: NodePort # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

contour:
  envoy:
    logLevel: debug
    service:
      type: NodePort
      nodePorts:
        http: $INGRESS_PORT
        https: $SECURED_INGRESS_PORT

cnrs:
  domain_name: "$APPS_DOMAIN_PREFIX.$MINIKUBE_IP.$DOMAIN"

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "$MINIKUBE_IP.$DOMAIN"
  app_config:
    app:
      baseUrl: http://tap-gui.$MINIKUBE_IP.$DOMAIN:$INGRESS_PORT
    catalog:
      locations:
        - type: url
          target: https://github.com/benwilcock/tap-gui-blank-catalog/blob/main/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.$MINIKUBE_IP.$DOMAIN:$INGRESS_PORT
      cors:
        origin: http://tap-gui.$MINIKUBE_IP.$DOMAIN:$INGRESS_PORT

grype:
  namespace: default
  targetImagePullSecret: registry-credentials

learningcenter:
  ingressDomain: $LEARNING_DOMAIN_PREFIX.$MINIKUBE_IP.$DOMAIN:$INGRESS_PORT

